id: A5B3A5BEE
title: A Song of Calling the Guru from Afar
type: translation
pechas:
- I07397191
- I87E4CB44
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:21.229691
  last_modified_at: 2023-01-04 11:52:21.229696
  collections:
  - Fifth Shamarpa
  - Works of Tibetan Masters
alignment_to_base:
  I07397191/DFC2: 8C43
  I87E4CB44/558F: 8C43
